allowBuilds:
  '@open-wa/wa-automate': true
  '@prisma/client': true
  '@prisma/engines': true
  '@whiskeysockets/baileys': true
  cloudflared: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  protobufjs: true
  puppeteer: true
  sharp: true
  unix-dgram: true
onlyBuiltDependencies:
  - '@open-wa/wa-automate'
  - '@prisma/client'
  - '@prisma/engines'
  - '@whiskeysockets/baileys'
  - cloudflared
  - esbuild
  - msgpackr-extract
  - prisma
  - protobufjs
  - puppeteer
  - sharp
  - unix-dgram
